from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Image, Spacer
from get_weather import get_5_day_forecast
import os
import sys

# Define the root directory for assets relative to the execution context.
# Assuming the script runs from /src or the main project root.
# For ReportLab to find local images, we must provide an absolute path or a path
# relative to the script's execution. We'll use a relative path here:
LOCAL_ASSETS_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'assets', 'weather')

# --- 1. Your Mock Weather Data (Now using local paths) ---
# NOTE: The icon_url now reflects the local file path as generated by get_weather.py
FORECAST_DATA = [
    # Example using the suggested 12 icons
    {'day': 'Sunday', 'location': 'Bryn Mawr, PA', 'description': 'Chance Snow then Partly Sunny', 'icon_url': os.path.join(LOCAL_ASSETS_ROOT, 'wi-rain-mix.png'), 'max_temp': 29, 'min_temp': 14},
    {'day': 'Monday', 'location': '', 'description': 'Mostly Sunny', 'icon_url': os.path.join(LOCAL_ASSETS_ROOT, 'wi-day-cloudy.png'), 'max_temp': 28, 'min_temp': 18},
    {'day': 'Tuesday', 'location': '', 'description': 'Mostly Cloudy', 'icon_url': os.path.join(LOCAL_ASSETS_ROOT, 'wi-cloudy.png'), 'max_temp': 30, 'min_temp': 22},
    {'day': 'Wednesday', 'location': '', 'description': 'Showers Likely', 'icon_url': os.path.join(LOCAL_ASSETS_ROOT, 'wi-rain.png'), 'max_temp': 41, 'min_temp': 27},
    {'day': 'Thursday', 'location': '', 'description': 'Clear and Windy', 'icon_url': os.path.join(LOCAL_ASSETS_ROOT, 'wi-strong-wind.png'), 'max_temp': 50, 'min_temp': 35}
]

# --- 2. Styles and Utility Functions ---

styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name='WeatherDay', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=10, alignment=1))
styles.add(ParagraphStyle(name='WeatherTemp', parent=styles['Normal'], fontSize=8, alignment=1, spaceAfter=2))
styles.add(ParagraphStyle(name='WeatherDesc', parent=styles['Normal'], fontSize=7, alignment=1))
styles.add(ParagraphStyle(name='ReportHeader', parent=styles['h1'], fontSize=16, alignment=1, spaceAfter=12))

# --- Removed External Icon Mapping/Fetching Logic ---
# The map_to_bw_icon function is no longer necessary as the data is pre-mapped.

def build_weather_flowable(forecast_data):
    """
    Creates the main ReportLab Table flowable for the 5-day weather forecast.
    """

    # 5 columns for 5 days
    col_width = 1.3 * inch
    table_data = []

    # Row 1: Day Name
    day_row = []
    for day_data in forecast_data:
        day_para = Paragraph(day_data['day'].upper(), styles['WeatherDay'])
        day_row.append(day_para)
    table_data.append(day_row)

    # Row 2: Icon and Min/Max Temperature (Stacked Vertically)
    icon_temp_row = []
    for day_data in forecast_data:

        # 1. Create the Icon flowable
        icon_path = day_data['icon_url']
        if not os.path.exists(icon_path):
             icon_flowable = Paragraph('[-? -]', styles['WeatherDesc'])
        else:
             icon_flowable = Image(
                 icon_path,
                 width=0.45*inch,  # Slightly larger icon since it has more room now
                 height=0.45*inch,
                 kind='proportional'
             )

        # 2. Create the Temperature text
        temp_text = f"<b>{day_data['max_temp']}°</b> / {day_data['min_temp']}°F"
        temp_para = Paragraph(temp_text, styles['WeatherTemp'])

        # 3. Create a nested table for this cell: 2 rows, 1 column (Icon over Temp)
        nested_table = Table(
            [[icon_flowable], [temp_para]],
            colWidths=[col_width - 0.2*inch], # Use most of the column width
            rowHeights=[0.5*inch, 0.2*inch]    # Top row for icon, bottom for temp
        )

        # Style the nested table to stack vertically and center
        nested_table.setStyle(TableStyle([
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (0,0), 'BOTTOM'), # Push icon toward the temp text
            ('VALIGN', (0,1), (0,1), 'TOP'),    # Push temp text toward the icon
            ('LEFTPADDING', (0,0), (-1,-1), 0),
            ('RIGHTPADDING', (0,0), (-1,-1), 0),
            ('BOTTOMPADDING', (0,0), (-1,-1), 2),
        ]))

        icon_temp_row.append(nested_table)

    table_data.append(icon_temp_row)

    # Row 3: Description (Terse)
    description_row = []
    for day_data in forecast_data:
        description_row.append(Paragraph(day_data['description'], styles['WeatherDesc']))
    table_data.append(description_row)

    # --- Create and Style the Main Table ---
    weather_table = Table(table_data, colWidths=[col_width] * 5)

    weather_table.setStyle(TableStyle([
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOX', (0,0), (-1,-1), 0.5, colors.black),
        ('LINEBEFORE', (1,0), (-1,-1), 0.25, colors.lightgrey),
        ('BACKGROUND', (0,0), (-1,0), colors.whitesmoke),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))

    return weather_table


def generate_test_screamsheet(filename="test_screamsheet_weather.pdf"):
    """
    Creates a sample 8.5x11 PDF to demonstrate the weather flowable.
    """
    doc = SimpleDocTemplate(filename, pagesize=letter)
    story = []

    # Header for the Report
    story.append(Paragraph("Daily Scream Sheet - Weather Integration Test", styles['ReportHeader']))
    story.append(Spacer(1, 0.1 * inch))

    # Ensure the assets path exists for the test to run smoothly
    if not os.path.isdir(LOCAL_ASSETS_ROOT):
        print(f"Error: Asset directory not found at {LOCAL_ASSETS_ROOT}")
        print("Please ensure your folder structure is /src/assets/weather/")
        return

    # Build the weather flowable
    forecast_data = get_5_day_forecast()
    weather_flowable = build_weather_flowable(forecast_data)

    # Add the weather flowable to the story
    story.append(weather_flowable)

    story.append(Spacer(1, 0.25 * inch))
    story.append(Paragraph("--- Main News Content Starts Here ---", styles['h3']))

    # Build the PDF
    doc.build(story)
    print(f"\nPDF generated successfully: {filename}")


if __name__ == '__main__':
    generate_test_screamsheet()
